#!/usr/bin/env node

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';
import { build } from 'esbuild';

const root = process.cwd();
const checkOnly = process.argv.includes('--check');
const generatedDir = path.join(root, 'src/mcp/apps/generated');

// Budgets account for the @modelcontextprotocol/ext-apps App SDK bundled into
// every standalone IIFE (~305 KB minified baseline: zod v4 + MCP Apps protocol
// schemas) plus the widget UI itself (~20 KB).
const WIDGET_BUDGET_BYTES = 384 * 1024;

ensureThemesData();

/**
 * Plan 10 §7.1: regenerate (or freshness-check) the widget theme catalog
 * before bundling so widgets always paint with current dashboard themes.
 */
function ensureThemesData() {
  const script = path.join(root, 'scripts/mcp-apps/gen-themes.mjs');
  const args = checkOnly ? [script, '--check'] : [script];
  const result = spawnSync(process.execPath, args, { stdio: 'inherit' });

  if (result.error) {
    console.error(`[FAIL] Could not run gen-themes.mjs: ${result.error.message}`);
    process.exit(1);
  }
  if (result.status !== 0) {
    console.error('[FAIL] Theme data generation failed; aborting widget build.');
    process.exit(result.status ?? 1);
  }
}

const widgets = [
  {
    name: 'presentation-list',
    title: 'Verto presentation workspace',
    entry: 'src/mcp/apps/components/presentation-list.ts',
    htmlFile: 'presentation-list.html',
    tsFile: 'presentation-list.ts',
    exportName: 'PRESENTATION_LIST_WIDGET_HTML',
    budgetBytes: WIDGET_BUDGET_BYTES,
  },
  {
    name: 'generation-progress',
    title: 'Verto generation progress',
    entry: 'src/mcp/apps/components/generation-progress.ts',
    htmlFile: 'generation-progress.html',
    tsFile: 'generation-progress.ts',
    exportName: 'GENERATION_PROGRESS_WIDGET_HTML',
    // Plan 10 §8/F7: the live-generation card bundles the shared slide
    // renderer for inline first-slide previews plus the auto-poll engine,
    // so it carries a dedicated budget instead of the standard one.
    budgetBytes: 416 * 1024,
  },
  {
    name: 'deck-preview',
    title: 'Verto deck preview',
    entry: 'src/mcp/apps/components/deck-preview.ts',
    htmlFile: 'deck-preview.html',
    tsFile: 'deck-preview.ts',
    exportName: 'DECK_PREVIEW_WIDGET_HTML',
    // Plan 10 §8/F6: the guided slide editor rides along with the preview
    // surface, so it carries a dedicated budget instead of the standard one.
    budgetBytes: 448 * 1024,
  },
  {
    name: 'action-result',
    title: 'Verto action result',
    entry: 'src/mcp/apps/components/action-result.ts',
    htmlFile: 'action-result.html',
    tsFile: 'action-result.ts',
    exportName: 'ACTION_RESULT_WIDGET_HTML',
    budgetBytes: WIDGET_BUDGET_BYTES,
  },
  // Plan 10 §8: presenter bundles renderer + stage + grid, so it carries a
  // dedicated larger budget instead of the standard one.
  {
    name: 'deck-live',
    title: 'Verto live presenter',
    entry: 'src/mcp/apps/components/deck-live.ts',
    htmlFile: 'deck-live.html',
    tsFile: 'deck-live.ts',
    exportName: 'DECK_LIVE_WIDGET_HTML',
    budgetBytes: 512 * 1024,
  },
  // Plan 10 F4/F5: theme studio (catalog + apply flow) and publish card
  // (celebration + QR + unpublish) wire the existing payload contracts.
  {
    name: 'theme-studio',
    title: 'Verto theme studio',
    entry: 'src/mcp/apps/components/theme-studio.ts',
    htmlFile: 'theme-studio.html',
    tsFile: 'theme-studio.ts',
    exportName: 'THEME_STUDIO_WIDGET_HTML',
    budgetBytes: WIDGET_BUDGET_BYTES,
  },
  {
    name: 'publish-card',
    title: 'Verto publish card',
    entry: 'src/mcp/apps/components/publish-card.ts',
    htmlFile: 'publish-card.html',
    tsFile: 'publish-card.ts',
    exportName: 'PUBLISH_CARD_WIDGET_HTML',
    budgetBytes: WIDGET_BUDGET_BYTES,
  },
];

await mkdir(generatedDir, { recursive: true });

const generatedArtifacts = [];
let hasFailure = false;

for (const widget of widgets) {
  const js = await bundleWidget(widget);
  const html = wrapHtml(widget.title, js);
  const htmlBytes = Buffer.byteLength(html, 'utf8');

  if (htmlBytes > widget.budgetBytes) {
    console.error(
      `[FAIL] ${widget.name} is ${htmlBytes} bytes, over budget ${widget.budgetBytes} bytes.`
    );
    hasFailure = true;
  } else {
    console.log(`[PASS] ${widget.name} is ${htmlBytes} bytes.`);
  }

  const htmlPath = path.join(generatedDir, widget.htmlFile);
  const tsPath = path.join(generatedDir, widget.tsFile);
  const ts = [
    '// Generated by scripts/mcp-apps/build-widgets.mjs. Do not edit by hand.',
    `export const ${widget.exportName} = ${JSON.stringify(html)};`,
    '',
  ].join('\n');

  generatedArtifacts.push({ filePath: htmlPath, content: html });
  generatedArtifacts.push({ filePath: tsPath, content: ts });
}

generatedArtifacts.push({
  filePath: path.join(generatedDir, 'index.ts'),
  content: [
    '// Generated by scripts/mcp-apps/build-widgets.mjs. Do not edit by hand.',
    "export { PRESENTATION_LIST_WIDGET_HTML } from './presentation-list';",
    "export { GENERATION_PROGRESS_WIDGET_HTML } from './generation-progress';",
    "export { DECK_PREVIEW_WIDGET_HTML } from './deck-preview';",
    "export { ACTION_RESULT_WIDGET_HTML } from './action-result';",
    "export { DECK_LIVE_WIDGET_HTML } from './deck-live';",
    "export { THEME_STUDIO_WIDGET_HTML } from './theme-studio';",
    "export { PUBLISH_CARD_WIDGET_HTML } from './publish-card';",
    '',
  ].join('\n'),
});

for (const artifact of generatedArtifacts) {
  const ok = await writeOrCheck(artifact.filePath, artifact.content);
  hasFailure = hasFailure || !ok;
}

if (hasFailure) {
  process.exit(1);
}

console.log(checkOnly
  ? 'MCP app widget generated artifacts are up to date.'
  : 'MCP app widget generated artifacts written.');

async function bundleWidget(widget) {
  const result = await build({
    absWorkingDir: root,
    entryPoints: [path.join(root, widget.entry)],
    bundle: true,
    write: false,
    minify: true,
    platform: 'browser',
    format: 'iife',
    target: ['es2020'],
    legalComments: 'none',
    sourcemap: false,
  });

  const output = result.outputFiles?.[0]?.text;
  if (!output) {
    throw new Error(`esbuild did not emit output for ${widget.name}.`);
  }

  return output.trim();
}

function wrapHtml(title, js) {
  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    `  <title>${escapeHtml(title)}</title>`,
    '</head>',
    '<body>',
    '  <script>',
    js,
    '  </script>',
    '</body>',
    '</html>',
    '',
  ].join('\n');
}

async function writeOrCheck(filePath, content) {
  if (!checkOnly) {
    await writeFile(filePath, content, 'utf8');
    return true;
  }

  let existing = '';
  try {
    existing = await readFile(filePath, 'utf8');
  } catch {
    console.error(`[FAIL] Missing generated artifact: ${relative(filePath)}`);
    return false;
  }

  if (existing !== content) {
    console.error(`[FAIL] Generated artifact is stale: ${relative(filePath)}`);
    return false;
  }

  console.log(`[PASS] Generated artifact is current: ${relative(filePath)}`);
  return true;
}

function escapeHtml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function relative(filePath) {
  return path.relative(root, filePath).replace(/\\/g, '/');
}
