#!/usr/bin/env node
/**
 * Generates src/mcp/apps/generated/themes-data.ts from the dashboard
 * `themes[]` catalog in src/lib/constants.ts (plan 10 §7.1).
 *
 * Widgets bundle this module so they can paint the deck's real theme tokens
 * without importing React/dashboard constants. Run automatically by
 * build-widgets.mjs; supports --check for freshness gates.
 *
 * Usage: node scripts/mcp-apps/gen-themes.mjs [--check]
 */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = process.cwd();
const checkOnly = process.argv.includes('--check');
const constantsPath = path.join(root, 'src/lib/constants.ts');
const outputPath = path.join(root, 'src/mcp/apps/generated/themes-data.ts');

const REQUIRED_FIELDS = ['name', 'fontFamily', 'fontColor', 'accentColor', 'backgroundColor', 'type'];

const source = await readFile(constantsPath, 'utf8');

const themes = parseThemesArray(source);

validate(themes);

const generated = renderModule(themes);

if (checkOnly) {
  let existing = '';
  try {
    existing = await readFile(outputPath, 'utf8');
  } catch {
    console.error('[FAIL] Missing generated artifact: src/mcp/apps/generated/themes-data.ts');
    process.exit(1);
  }
  if (existing !== generated) {
    console.error('[FAIL] Generated artifact is stale: src/mcp/apps/generated/themes-data.ts');
    process.exit(1);
  }
  console.log(`[PASS] Generated themes data is current (${themes.length} themes).`);
} else {
  await writeFile(outputPath, generated, 'utf8');
  console.log(`[PASS] Generated themes data written (${themes.length} themes).`);
}

/**
 * Extracts the `export const themes: Theme[] = [...];` literal and evaluates
 * it as plain JavaScript data (the catalog is pure object literals — no
 * imports, function calls, or template strings inside).
 */
function parseThemesArray(sourceText) {
  const marker = 'export const themes';
  const markerIndex = sourceText.indexOf(marker);
  if (markerIndex === -1) {
    fail('Could not find `export const themes` in src/lib/constants.ts.');
  }

  const assignmentIndex = sourceText.indexOf('=', markerIndex);
  const arrayStart = sourceText.indexOf('[', assignmentIndex);
  if (arrayStart === -1) {
    fail('Could not find opening bracket of themes array.');
  }

  const endMatch = /^];/m.exec(sourceText.slice(arrayStart));
  if (!endMatch) {
    fail('Could not find closing bracket of themes array.');
  }
  const arrayEnd = arrayStart + endMatch.index;

  // Slice only the `[...]` literal — the trailing `;` would break evaluation.
  const arrayText = sourceText.slice(arrayStart, arrayEnd + 1);

  try {
    const evaluated = new Function(`"use strict";\nreturn (${arrayText});`)();
    if (!Array.isArray(evaluated)) {
      fail('Themes array did not evaluate to an array.');
    }
    return evaluated;
  } catch (error) {
    fail(`Themes array is not plain evaluable data: ${error.message}`);
    return [];
  }
}

function validate(themeList) {
  if (themeList.length < 60) {
    fail(`Expected the full 65-theme catalog, found ${themeList.length}.`);
  }

  const names = new Set();
  for (const theme of themeList) {
    for (const field of REQUIRED_FIELDS) {
      if (typeof theme[field] !== 'string' || !theme[field]) {
        fail(`Theme is missing required field "${field}": ${JSON.stringify(theme.name ?? theme)}`);
      }
    }
    if (theme.type !== 'light' && theme.type !== 'dark') {
      fail(`Theme "${theme.name}" has invalid type: ${theme.type}`);
    }
    if (names.has(theme.name)) {
      fail(`Duplicate theme name: ${theme.name}`);
    }
    names.add(theme.name);
  }
}

function renderModule(themeList) {
  const slim = themeList.map((theme) => ({
    name: theme.name,
    type: theme.type,
    fontFamily: theme.fontFamily,
    fontColor: theme.fontColor,
    accentColor: theme.accentColor,
    backgroundColor: theme.backgroundColor,
    slideBackgroundColor: orUndefined(theme.slideBackgroundColor),
    gradientBackground: orUndefined(theme.gradientBackground),
    headingFontFamily: orUndefined(theme.headingFontFamily),
    accentGradient: orUndefined(theme.accentGradient),
    surfaceColor: orUndefined(theme.surfaceColor),
    mutedColor: orUndefined(theme.mutedColor),
    borderRadius: orUndefined(theme.borderRadius),
    shadowPreset: orUndefined(theme.shadowPreset),
  }));

  return [
    '// Generated by scripts/mcp-apps/gen-themes.mjs from src/lib/constants.ts themes[].',
    '// Do not edit by hand — rerun `npm run mcp:apps:build` instead.',
    '',
    '/** Slimmed port of the dashboard Theme shape (src/lib/types.ts). */',
    'export interface VertoThemeData {',
    "  name: string;",
    "  type: 'light' | 'dark';",
    '  fontFamily: string;',
    '  fontColor: string;',
    '  accentColor: string;',
    '  backgroundColor: string;',
    '  slideBackgroundColor?: string;',
    '  gradientBackground?: string;',
    '  headingFontFamily?: string;',
    '  accentGradient?: string;',
    '  surfaceColor?: string;',
    '  mutedColor?: string;',
    '  borderRadius?: string;',
    "  shadowPreset?: 'none' | 'soft' | 'medium' | 'dramatic';",
    '}',
    '',
    `export const VERTO_THEMES: VertoThemeData[] = ${JSON.stringify(slim, null, 2)};`,
    '',
  ].join('\n');
}

function orUndefined(value) {
  return typeof value === 'string' && value.trim() ? value : undefined;
}

function fail(message) {
  console.error(`[FAIL] gen-themes: ${message}`);
  process.exit(1);
}
